name: flutterl10nmanager
description: A package to help manage multiple languages in a Flutter project.
version: 1.0.9
homepage: https://github.com/wamphlett/flutterl10nmanager
author: Warren Amphlett <warren@remarkablelives.co.uk>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.4.2
  ansicolor: ^2.0.1
  csv: ^5.0.2
  intl: ^0.18.1

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0

executables:
  flutterl10nmanager: main
